apiVersion: v1
kind: Secret
metadata:
  name: nebula-app-secret
  namespace: nebula
type: Opaque
stringData:
  DB_NAME: mydatabase
  DB_USER: admin
  DB_PASSWORD: REPLACE_ME_DB_PASSWORD
  DB_HOST: nebula-postgresql
  DB_PORT: "5432"
  REDIS_HOST: nebula-redis
  REDIS_PORT: "6379"

  DJANGO_SECRET_KEY: REPLACE_ME_DJANGO_SECRET
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: nebula.prod.home,localhost,127.0.0.1

  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_PASSWORD: REPLACE_ME_ADMIN_PASSWORD
  DJANGO_SUPERUSER_EMAIL: admin@example.com

  SSH_PUBLIC_KEY_ENCRYPTION_KEY: ""
  SSH_PRIVATE_KEY_B64: REPLACE_ME_WITH_BASE64_PRIVATE_KEY
  SSH_KEY_CONTAINER_PATH: /run/secrets/ssh_key
  SSH_KEY_PATH: /run/secrets/ssh_key
  SSH_KEY_PASSPHRASE: ""
  ESXI_SSH_KEY_PATH: /run/secrets/ssh_key
  KVM_SSH_KEY_PATH: /run/secrets/ssh_key
  HYPERVISOR_PLUGIN_MODULES: ""
