{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebula.secretName" . }}
  namespace: {{ include "nebula.namespace" . }}
  labels:
    {{- include "nebula.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.database.auth.database | quote }}
  DB_USER: {{ .Values.database.auth.username | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_HOST: {{ include "nebula.dbHost" . | quote }}
  DB_PORT: {{ ternary (.Values.database.port | toString) (.Values.externalDatabase.port | toString) .Values.database.enabled | quote }}
  REDIS_HOST: {{ include "nebula.redisHost" . | quote }}
  REDIS_PORT: {{ ternary (.Values.redis.port | toString) (.Values.externalRedis.port | toString) .Values.redis.enabled | quote }}
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | quote }}
  DJANGO_DEBUG: {{ .Values.app.debug | toString | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.app.allowedHosts | quote }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.secrets.djangoSuperuserUsername | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.secrets.djangoSuperuserPassword | quote }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.secrets.djangoSuperuserEmail | quote }}
  SSH_PUBLIC_KEY_ENCRYPTION_KEY: {{ .Values.secrets.sshPublicKeyEncryptionKey | quote }}
  SSH_PRIVATE_KEY_B64: {{ .Values.secrets.sshPrivateKeyB64 | quote }}
  SSH_KEY_CONTAINER_PATH: {{ .Values.secrets.sshKeyContainerPath | quote }}
  SSH_KEY_PATH: {{ .Values.secrets.sshKeyContainerPath | quote }}
  SSH_KEY_PASSPHRASE: {{ .Values.secrets.sshKeyPassphrase | quote }}
  ESXI_SSH_KEY_PATH: {{ .Values.secrets.sshKeyContainerPath | quote }}
  KVM_SSH_KEY_PATH: {{ .Values.secrets.sshKeyContainerPath | quote }}
  HYPERVISOR_PLUGIN_MODULES: {{ .Values.app.hypervisorPluginModules | quote }}
{{- end }}
