{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebula.fullname" . }}-web
  namespace: {{ include "nebula.namespace" . }}
  labels:
    {{- include "nebula.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "nebula.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: http
{{- end }}
