# Generated by Django 4.2.30 on 2026-04-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. M920q-Node-01', max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('power_state', models.CharField(default='Unknown', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_usage', models.IntegerField(default=0)),
                ('memory_usage', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='manager.host')),
            ],
            options={
                'unique_together': {('host', 'vmid')},
            },
        ),
    ]
