# Generated by Django 4.2.30 on 2026-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='created_at',
        ),
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='username',
            field=models.CharField(default='root', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='VirtualMachine',
        ),
    ]
