# Generated by Django 4.2.30 on 2026-04-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_host_created_at_host_password_host_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
