# Generated by Django 4.2.30 on 2026-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_host_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
