# Generated by Django 4.2.30 on 2026-04-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_host_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('power_state', models.CharField(default='Unknown', max_length=50)),
                ('vmx_path', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='manager.host')),
            ],
            options={
                'verbose_name': 'Virtual Machine',
                'verbose_name_plural': 'Virtual Machines',
                'unique_together': {('vmid', 'host')},
            },
        ),
    ]
