# Generated by Django 4.2.30 on 2026-04-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_virtualmachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='guest_os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='host_cpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='host_memory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='used_space',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
