# Generated by Django 4.2.30 on 2026-04-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_virtualmachine_guest_os_virtualmachine_host_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='host',
            name='license_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='license_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='os_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='processor_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='services_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='host',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
