# Generated by Django 4.2.30 on 2026-04-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_host_last_sync_host_license_key_host_license_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpu_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='memory_gb',
            field=models.IntegerField(default=0),
        ),
    ]
