# Generated by Django 4.2.30 on 2026-04-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_host_cpu_count_host_memory_gb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='host_cpu',
            new_name='tools_status',
        ),
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='host_memory',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='virtualmachine',
            name='used_space',
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='cpu_usage_mhz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='distro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='hw_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='kernel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='mem_active_mb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='memory_mb',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='networks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='num_cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='overall_status',
            field=models.CharField(default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='storage_provisioned_gb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='storage_used_gb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='uptime_human',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
