# Generated by Django 4.2.30 on 2026-04-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_rename_host_cpu_virtualmachine_tools_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='tools_running',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
