# Generated by Django 6.0.4 on 2026-04-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_host_ssh_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='network_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='host',
            name='storage_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
